### PR TITLE
Add local time before messages

### PR DESCRIPTION
**Pull request by aritra1911**
There's a `TODO` in `time.cpp`, so don't merge yet.

### CODE REVIEW

**Comment by aritra1911** [comment]
Alright, now you may test it a lil. bit maybe change a few things... If it looks good, you may merge this.

**Review by CodeOn-ArK — COMMENTED** [review]
So have you tested any sample code or directly commiting here?

**Comment by aritra1911** [comment]
All tested.

**Review by CodeOn-ArK — APPROVED** [review]
fyn

**Pull request merged**
